CI: comment with rspec-stderr (#2330)
We should avoid introducing noisy warnings in our test output.
Often the warnings (deprecation warnings) are added by Dependabot upgrades. This way it will not merge PR adding noise automatically.

https://app.asana.com/0/1142794766483633/1208315235207762

`continue-on-error` because we do not want this marked as the primary failure (scrolled to and opened), if any other steps failed.
It will still output the warnings as github actions markup errors, so they will be visible elsewhere.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -219,8 +219,16 @@ jobs:
         run: |
           bin/rake db:create
           bin/rake db:schema:load
-      - name: rspec
-        run: bin/rspec --format RSpec::Github::Formatter --format progress
+      - run: bin/rspec --format RSpec::Github::Formatter --format documentation 2> >(tee /tmp/stderr.log >&2)
+        id: rspec
+      - name: stderr
+        if: ${{ !cancelled() }}
+        run: |
+          touch /tmp/stderr.log
+          errors=$(cat /tmp/stderr.log | grep -vf .github/ci-ignored-stderr.txt | sed 's/\(.*\)/::error::\1/')
+          echo "$errors"
+          test -z "$errors"
+        continue-on-error: ${{ steps.rspec.conclusion == 'failure' }}
       - name: Archive capybara artifacts
         uses: actions/upload-artifact@v4
         if: failure()
